FROM pytorch/pytorch

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libosmesa6 \
    freeglut3-dev \
    python3 \
    python3-pip \
    libfreetype6 \
    curl \
    git

# fixing ruamel.yaml
RUN conda install ruamel.yaml -y

ADD requirements.txt /tmp/
RUN pip3 install --upgrade pip && pip3 install --no-cache-dir -r /tmp/requirements.txt
RUN pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
