image:
  size_lstm: 128
  size_unet: 64
  dataset_lenghtn: 5000

device:
  to: cpu

convlstm:
  epoches: 100
  change_lr: [50,90]
  lr: [1e-4, 1e-5, 1e-6]
  train_path: './data/data_pointstar_mixed_1_100x100.pickle'
  val_path: './data/data_pointstar_mixed_1_100x100.pickle'
  test_path: './data/data_pointstar_mixed_1_100x100.pickle'
  checkpoints_path: '/home/zoya/PycharmProjects/fswp/checkpoints/convlstm'
  wights_path: '/home/zoya/PycharmProjects/fswp/checkpoints/convlstm/CONV_LSTM_run_EricWright_94ed9438-8fae-4fc8-8afa-85409d0c6f46.pth'


unet:
  epoches: 200
  change_lr: [  15,80 ]
  lr: [  1e-3, 1e-4, 1e-5]
  train_path: './data/data_for_unet_star.pickle'
  batch_size: 32
  val_batch_size: 16
  checkpoints_path: '../checkpoints/unet'
  wights_path: '/home/zoya/PycharmProjects/fswp/checkpoints/unet/UNET_run_KathyCorbin_3c4cf0f6-632b-4a5e-8ac8-5175a0ee9d2c.pth'

